### ISSUE TITLE
DIRT\2D workflow issue

### ISSUE THREAD

**Issue by rhallmark15** [Computational-Plant-Science/plantit#368]
**PlantIT report:** Created task ef5e4192-dbd8-472e-8c87-1d66ed05f9db on Puma_GPU
Failed to prep environment: Traceback (most recent call last):
File "/code/plantit/plantit/celery_tasks.py", line 158, in prep_environment
with ssh:
File "/code/plantit/plantit/ssh.py", line 70, in __enter__
jump_client.connect(self.jump_host, self.jump_port, self.username, pkey=key, timeout=self.timeout)
File "/usr/local/lib/python3.10/site-packages/paramiko/client.py", line 406, in connect
t.start_client(timeout=timeout)
File "/usr/local/lib/python3.10/site-packages/paramiko/transport.py", line 698, in start_client
raise e
File "/usr/local/lib/python3.10/site-packages/paramiko/transport.py", line 2101, in run
self.packetizer.start_handshake(self.handshake_timeout)
File "/usr/local/lib/python3.10/site-packages/paramiko/packet.py", line 252, in start_handshake
self.__timer.start()
File "/usr/local/lib/python3.10/threading.py", line 935, in start
_start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

Task is started and then failed within first few minutes of run

**Comment by koalaspirit** [comment]
Hi, it should be working now. We needed to restart the celery worker.

**Comment by rhallmark15** [comment]
Thank you!
